Add query params to analitics query page
tonkeeper/ton-console pull request #73
Opened 2024-06-10 14:55 UTC by mois-ilya

2024-06-11 12:19 UTC, siandreev requested changes

2024-06-11 12:19 UTC, siandreev commented on src/features/analytics/model/analytics-query-request.store.ts
> +    private _network = DTOChain.DTOMainnet;
Думаю, тип лучше оставить как было. В другом эндпоинте может быть другой сгенерированный енум, и тогда в проекте будет несколько типов для обозначения тестнет/мейннет. Предлагаю просто смапить то что приходит с бэка во внутрипроектовый тип

2024-06-17 13:16 UTC, mois-ilya commented on src/features/analytics/model/analytics-query-request.store.ts
> +    private _network = DTOChain.DTOMainnet;
>  другом эндпоинте может быть другой сгенерированный енум

Если такое случится, то первым действием будет предложение переиспользования типа в схеме, а если это будет сделать нельзя, тогда будет иметь смысл переписать

Сейчас маппинг добавляет кодовой базы и усложняет понимание связи между API и внутренней логикой

2024-06-18 10:40 UTC, siandreev commented on src/features/analytics/model/analytics-query-request.store.ts
> +    private _network = DTOChain.DTOMainnet;
> тогда будет иметь смысл переписать
Чтобы потом не переписывать, лучше оставить как было. К тому же, сеть может использоваться не только в контексте апи бэкэнда, например, в тон коннекте

2024-06-18 11:04 UTC, mois-ilya commented on src/features/analytics/model/analytics-query-request.store.ts
> +    private _network = DTOChain.DTOMainnet;
Норм будет если Network станет enum вместо union?
Т.к. вспомнил что перешел на него в том числе, т.к. я хотел иметь не просто тип а перечень возможных значений [тут](https://github.com/tonkeeper/ton-console/pull/73/files#r1644264353)

2024-06-18 11:31 UTC, siandreev commented on src/pages/analytics/query/index.tsx
> +        const isValidNetwork = Object.values(DTOChain).includes(typedNetwork);
Можно тогда сделать выводимый юнион

```
export const Network = ['mainnet', 'testnet'] as const;
export type Network = (typeof Network)[number];
```

2024-06-18 12:29 UTC, merged